### PR TITLE
feat: Android 14 Support added

### PR DESCRIPTION
**Pull request by hazmi-e205**
> Whether this PR is eventually merged or not, Sonic will thank you very much for your contribution. 
> 
> 无论此PR最终是否合并，Sonic组织都非常感谢您的贡献。

### Checklist

- [x] The title starts with fix, fea, or doc. | 标题为fix、feat或doc开头。
- [x] I have checked that there are no duplicate pull requests with this request. | 我已检查没有与此请求重复的拉取请求。
- [x] I have considered and confirmed that this submission is valuable to others. | 我已经考虑过，并确认这份呈件对其他人很有价值。
- [x] I accept that this submission may not be used. | 我接受此提交可能不会被使用。

### Description
- Ported InputManagerGlobalEventInjector to support input event for Android 14
- Fixed crash SonicKeyboard on Android 14 because behavior changes of registerReceiver method
- Fixed crash SonicManagerServiceV2 on Android 14 because behavior changes of startForeground method
- Updated targetSdk and compileSdk to 34
- Updated AGP to 8.2.2 and Gradle 8.6
- Removed duplicate permissions

### CODE REVIEW

**Review by ZhouYixun — COMMENTED** [review]
ap

**Comment by ZhouYixun** [comment]
https://github.com/SonicCloudOrg/sonic-android-apk/actions/runs/8001005334/job/21851547381?pr=75

Checking failed. @hazmi-e205

**Comment by hazmi-e205** [comment]
Require OpenJDK 17 to build using latest Gradle

**Comment by hazmi-e205** [comment]
> https://github.com/SonicCloudOrg/sonic-android-apk/actions/runs/8001005334/job/21851547381?pr=75
> 
> Checking failed. @hazmi-e205


Require OpenJDK 17 to build using latest Gradle
where I can fix the CI?

**Comment by ZhouYixun** [comment]
> > https://github.com/SonicCloudOrg/sonic-android-apk/actions/runs/8001005334/job/21851547381?pr=75
> > Checking failed. @hazmi-e205
> 
> Require OpenJDK 17 to build using latest Gradle where I can fix the CI?

https://github.com/SonicCloudOrg/sonic-android-apk/blob/main/.github/workflows/android.yml

Remember you should make sure apk can work with low Android version like Android 5-10 (if possible )

**Comment by hazmi-e205** [comment]
> > > https://github.com/SonicCloudOrg/sonic-android-apk/actions/runs/8001005334/job/21851547381?pr=75
> > > Checking failed. @hazmi-e205
> > 
> > 
> > Require OpenJDK 17 to build using latest Gradle where I can fix the CI?
> 
> https://github.com/SonicCloudOrg/sonic-android-apk/blob/main/.github/workflows/android.yml
> 
> Remember you should make sure apk can work with low Android version like Android 5-10 (if possible )

Thanks for remaining me, will check it in my Android 7 device

**Comment by ZhouYixun** [comment]
thanks！

**Comment by hazmi-e205** [comment]
Tested in Android 7 and 14 with my latest commit, and both works

**Comment by ZhouYixun** [comment]
https://github.com/SonicCloudOrg/sonic-android-apk/releases/tag/v2.0.8

**Pull request merged**
